
create table subject(
	id serial primary key,
	name varchar(50),
	code int,
	course_type varchar(50),
	credits int,
	section char(2)
)
select * from subject
insert into subject values(1,'python',101,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'theory',2,'A')

select * from subject
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
select * from subject
insert into subject values(4,'biomedical',104,'theory',1,'A')
select * from subject
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('drawing',108,'theory',1,'A')
select * from subject
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject values(11,'english',109,'theory',1,'A'),(12,'computer',110,'practical',3,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject values(21,'history',111,'practical',1,'C'),(22,'science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')

insert into subject(name,code,course_type,credits,section) values ('automobile',102,'theory',2,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')

insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')

insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('history',111,'practical',1,'C')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('history',111,'practical',1,'C')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('history',111,'practical',1,'C')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('science',112,'theory',3,'B')
insert into subject(name,code,course_type,credits,section) values ('data_science',105,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('automobile',102,'practical',2,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('biomedical',104,'practical',1,'A')
insert into subject(name,code,course_type,credits,section) values ('power_industry',103,'theory',3,'A')
insert into subject(name,code,course_type,credits,section) values ('electronics',106,'theory',1,'A')
insert into subject(name,code,course_type,credits,section) values ('circuit_design',107,'theory',1,'A')

select * from subject

